//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPWebStream.TVEInteraction {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebChannel", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebChannel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MPWebStream.TVEInteraction.WebChannelGroup CurrentGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MPWebStream.TVEInteraction.WebProgram CurrentProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EpgHasGapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FreeToAirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GrabEpgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GroupNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRadioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastGrabTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MPWebStream.TVEInteraction.WebProgram NextProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimesWatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TotalTimeWatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisibleInGuideField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MPWebStream.TVEInteraction.WebChannelGroup CurrentGroup {
            get {
                return this.CurrentGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentGroupField, value) != true)) {
                    this.CurrentGroupField = value;
                    this.RaisePropertyChanged("CurrentGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MPWebStream.TVEInteraction.WebProgram CurrentProgram {
            get {
                return this.CurrentProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentProgramField, value) != true)) {
                    this.CurrentProgramField = value;
                    this.RaisePropertyChanged("CurrentProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EpgHasGaps {
            get {
                return this.EpgHasGapsField;
            }
            set {
                if ((this.EpgHasGapsField.Equals(value) != true)) {
                    this.EpgHasGapsField = value;
                    this.RaisePropertyChanged("EpgHasGaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreeToAir {
            get {
                return this.FreeToAirField;
            }
            set {
                if ((this.FreeToAirField.Equals(value) != true)) {
                    this.FreeToAirField = value;
                    this.RaisePropertyChanged("FreeToAir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GrabEpg {
            get {
                return this.GrabEpgField;
            }
            set {
                if ((this.GrabEpgField.Equals(value) != true)) {
                    this.GrabEpgField = value;
                    this.RaisePropertyChanged("GrabEpg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GroupNames {
            get {
                return this.GroupNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNamesField, value) != true)) {
                    this.GroupNamesField = value;
                    this.RaisePropertyChanged("GroupNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChannel {
            get {
                return this.IdChannelField;
            }
            set {
                if ((this.IdChannelField.Equals(value) != true)) {
                    this.IdChannelField = value;
                    this.RaisePropertyChanged("IdChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRadio {
            get {
                return this.IsRadioField;
            }
            set {
                if ((this.IsRadioField.Equals(value) != true)) {
                    this.IsRadioField = value;
                    this.RaisePropertyChanged("IsRadio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTv {
            get {
                return this.IsTvField;
            }
            set {
                if ((this.IsTvField.Equals(value) != true)) {
                    this.IsTvField = value;
                    this.RaisePropertyChanged("IsTv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastGrabTime {
            get {
                return this.LastGrabTimeField;
            }
            set {
                if ((this.LastGrabTimeField.Equals(value) != true)) {
                    this.LastGrabTimeField = value;
                    this.RaisePropertyChanged("LastGrabTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MPWebStream.TVEInteraction.WebProgram NextProgram {
            get {
                return this.NextProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.NextProgramField, value) != true)) {
                    this.NextProgramField = value;
                    this.RaisePropertyChanged("NextProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimesWatched {
            get {
                return this.TimesWatchedField;
            }
            set {
                if ((this.TimesWatchedField.Equals(value) != true)) {
                    this.TimesWatchedField = value;
                    this.RaisePropertyChanged("TimesWatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TotalTimeWatched {
            get {
                return this.TotalTimeWatchedField;
            }
            set {
                if ((this.TotalTimeWatchedField.Equals(value) != true)) {
                    this.TotalTimeWatchedField = value;
                    this.RaisePropertyChanged("TotalTimeWatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisibleInGuide {
            get {
                return this.VisibleInGuideField;
            }
            set {
                if ((this.VisibleInGuideField.Equals(value) != true)) {
                    this.VisibleInGuideField = value;
                    this.RaisePropertyChanged("VisibleInGuide");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebChannelGroup", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebChannelGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortOrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGroup {
            get {
                return this.IdGroupField;
            }
            set {
                if ((this.IdGroupField.Equals(value) != true)) {
                    this.IdGroupField = value;
                    this.RaisePropertyChanged("IdGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SortOrder {
            get {
                return this.SortOrderField;
            }
            set {
                if ((this.SortOrderField.Equals(value) != true)) {
                    this.SortOrderField = value;
                    this.RaisePropertyChanged("SortOrder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebProgram", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebProgram : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodeNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodePartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasConflictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPartialRecordingSeriesPendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingManualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingOnceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingOncePendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingSeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingSeriesPendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NotifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OriginalAirDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentalRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StarRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassificationField, value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodeName {
            get {
                return this.EpisodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodeNameField, value) != true)) {
                    this.EpisodeNameField = value;
                    this.RaisePropertyChanged("EpisodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodeNum {
            get {
                return this.EpisodeNumField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodeNumField, value) != true)) {
                    this.EpisodeNumField = value;
                    this.RaisePropertyChanged("EpisodeNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodeNumber {
            get {
                return this.EpisodeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodeNumberField, value) != true)) {
                    this.EpisodeNumberField = value;
                    this.RaisePropertyChanged("EpisodeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodePart {
            get {
                return this.EpisodePartField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodePartField, value) != true)) {
                    this.EpisodePartField = value;
                    this.RaisePropertyChanged("EpisodePart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasConflict {
            get {
                return this.HasConflictField;
            }
            set {
                if ((this.HasConflictField.Equals(value) != true)) {
                    this.HasConflictField = value;
                    this.RaisePropertyChanged("HasConflict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChannel {
            get {
                return this.IdChannelField;
            }
            set {
                if ((this.IdChannelField.Equals(value) != true)) {
                    this.IdChannelField = value;
                    this.RaisePropertyChanged("IdChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProgram {
            get {
                return this.IdProgramField;
            }
            set {
                if ((this.IdProgramField.Equals(value) != true)) {
                    this.IdProgramField = value;
                    this.RaisePropertyChanged("IdProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPartialRecordingSeriesPending {
            get {
                return this.IsPartialRecordingSeriesPendingField;
            }
            set {
                if ((this.IsPartialRecordingSeriesPendingField.Equals(value) != true)) {
                    this.IsPartialRecordingSeriesPendingField = value;
                    this.RaisePropertyChanged("IsPartialRecordingSeriesPending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecording {
            get {
                return this.IsRecordingField;
            }
            set {
                if ((this.IsRecordingField.Equals(value) != true)) {
                    this.IsRecordingField = value;
                    this.RaisePropertyChanged("IsRecording");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecordingManual {
            get {
                return this.IsRecordingManualField;
            }
            set {
                if ((this.IsRecordingManualField.Equals(value) != true)) {
                    this.IsRecordingManualField = value;
                    this.RaisePropertyChanged("IsRecordingManual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecordingOnce {
            get {
                return this.IsRecordingOnceField;
            }
            set {
                if ((this.IsRecordingOnceField.Equals(value) != true)) {
                    this.IsRecordingOnceField = value;
                    this.RaisePropertyChanged("IsRecordingOnce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecordingOncePending {
            get {
                return this.IsRecordingOncePendingField;
            }
            set {
                if ((this.IsRecordingOncePendingField.Equals(value) != true)) {
                    this.IsRecordingOncePendingField = value;
                    this.RaisePropertyChanged("IsRecordingOncePending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecordingSeries {
            get {
                return this.IsRecordingSeriesField;
            }
            set {
                if ((this.IsRecordingSeriesField.Equals(value) != true)) {
                    this.IsRecordingSeriesField = value;
                    this.RaisePropertyChanged("IsRecordingSeries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecordingSeriesPending {
            get {
                return this.IsRecordingSeriesPendingField;
            }
            set {
                if ((this.IsRecordingSeriesPendingField.Equals(value) != true)) {
                    this.IsRecordingSeriesPendingField = value;
                    this.RaisePropertyChanged("IsRecordingSeriesPending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Notify {
            get {
                return this.NotifyField;
            }
            set {
                if ((this.NotifyField.Equals(value) != true)) {
                    this.NotifyField = value;
                    this.RaisePropertyChanged("Notify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OriginalAirDate {
            get {
                return this.OriginalAirDateField;
            }
            set {
                if ((this.OriginalAirDateField.Equals(value) != true)) {
                    this.OriginalAirDateField = value;
                    this.RaisePropertyChanged("OriginalAirDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentalRating {
            get {
                return this.ParentalRatingField;
            }
            set {
                if ((this.ParentalRatingField.Equals(value) != true)) {
                    this.ParentalRatingField = value;
                    this.RaisePropertyChanged("ParentalRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeriesNum {
            get {
                return this.SeriesNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesNumField, value) != true)) {
                    this.SeriesNumField = value;
                    this.RaisePropertyChanged("SeriesNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StarRating {
            get {
                return this.StarRatingField;
            }
            set {
                if ((this.StarRatingField.Equals(value) != true)) {
                    this.StarRatingField = value;
                    this.RaisePropertyChanged("StarRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebRecording", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebRecording : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodeNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpisodePartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRecordingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdscheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeepUntilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime KeepUntilDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShouldBeDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StopTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimesWatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodeName {
            get {
                return this.EpisodeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodeNameField, value) != true)) {
                    this.EpisodeNameField = value;
                    this.RaisePropertyChanged("EpisodeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodeNum {
            get {
                return this.EpisodeNumField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodeNumField, value) != true)) {
                    this.EpisodeNumField = value;
                    this.RaisePropertyChanged("EpisodeNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodeNumber {
            get {
                return this.EpisodeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodeNumberField, value) != true)) {
                    this.EpisodeNumberField = value;
                    this.RaisePropertyChanged("EpisodeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EpisodePart {
            get {
                return this.EpisodePartField;
            }
            set {
                if ((object.ReferenceEquals(this.EpisodePartField, value) != true)) {
                    this.EpisodePartField = value;
                    this.RaisePropertyChanged("EpisodePart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChannel {
            get {
                return this.IdChannelField;
            }
            set {
                if ((this.IdChannelField.Equals(value) != true)) {
                    this.IdChannelField = value;
                    this.RaisePropertyChanged("IdChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRecording {
            get {
                return this.IdRecordingField;
            }
            set {
                if ((this.IdRecordingField.Equals(value) != true)) {
                    this.IdRecordingField = value;
                    this.RaisePropertyChanged("IdRecording");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServer {
            get {
                return this.IdServerField;
            }
            set {
                if ((this.IdServerField.Equals(value) != true)) {
                    this.IdServerField = value;
                    this.RaisePropertyChanged("IdServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idschedule {
            get {
                return this.IdscheduleField;
            }
            set {
                if ((this.IdscheduleField.Equals(value) != true)) {
                    this.IdscheduleField = value;
                    this.RaisePropertyChanged("Idschedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManual {
            get {
                return this.IsManualField;
            }
            set {
                if ((this.IsManualField.Equals(value) != true)) {
                    this.IsManualField = value;
                    this.RaisePropertyChanged("IsManual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecording {
            get {
                return this.IsRecordingField;
            }
            set {
                if ((this.IsRecordingField.Equals(value) != true)) {
                    this.IsRecordingField = value;
                    this.RaisePropertyChanged("IsRecording");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeepUntil {
            get {
                return this.KeepUntilField;
            }
            set {
                if ((this.KeepUntilField.Equals(value) != true)) {
                    this.KeepUntilField = value;
                    this.RaisePropertyChanged("KeepUntil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime KeepUntilDate {
            get {
                return this.KeepUntilDateField;
            }
            set {
                if ((this.KeepUntilDateField.Equals(value) != true)) {
                    this.KeepUntilDateField = value;
                    this.RaisePropertyChanged("KeepUntilDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeriesNum {
            get {
                return this.SeriesNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesNumField, value) != true)) {
                    this.SeriesNumField = value;
                    this.RaisePropertyChanged("SeriesNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShouldBeDeleted {
            get {
                return this.ShouldBeDeletedField;
            }
            set {
                if ((this.ShouldBeDeletedField.Equals(value) != true)) {
                    this.ShouldBeDeletedField = value;
                    this.RaisePropertyChanged("ShouldBeDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StopTime {
            get {
                return this.StopTimeField;
            }
            set {
                if ((this.StopTimeField.Equals(value) != true)) {
                    this.StopTimeField = value;
                    this.RaisePropertyChanged("StopTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimesWatched {
            get {
                return this.TimesWatchedField;
            }
            set {
                if ((this.TimesWatchedField.Equals(value) != true)) {
                    this.TimesWatchedField = value;
                    this.RaisePropertyChanged("TimesWatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebSchedule", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BitRateModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CanceledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DoesUseEpisodeManagementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdParentScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime KeepDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeepMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxAiringsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostRecordIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PreRecordIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QualityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QualityTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecommendedCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScheduleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BitRateMode {
            get {
                return this.BitRateModeField;
            }
            set {
                if ((this.BitRateModeField.Equals(value) != true)) {
                    this.BitRateModeField = value;
                    this.RaisePropertyChanged("BitRateMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Canceled {
            get {
                return this.CanceledField;
            }
            set {
                if ((this.CanceledField.Equals(value) != true)) {
                    this.CanceledField = value;
                    this.RaisePropertyChanged("Canceled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Directory {
            get {
                return this.DirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryField, value) != true)) {
                    this.DirectoryField = value;
                    this.RaisePropertyChanged("Directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DoesUseEpisodeManagement {
            get {
                return this.DoesUseEpisodeManagementField;
            }
            set {
                if ((this.DoesUseEpisodeManagementField.Equals(value) != true)) {
                    this.DoesUseEpisodeManagementField = value;
                    this.RaisePropertyChanged("DoesUseEpisodeManagement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChannel {
            get {
                return this.IdChannelField;
            }
            set {
                if ((this.IdChannelField.Equals(value) != true)) {
                    this.IdChannelField = value;
                    this.RaisePropertyChanged("IdChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdParentSchedule {
            get {
                return this.IdParentScheduleField;
            }
            set {
                if ((this.IdParentScheduleField.Equals(value) != true)) {
                    this.IdParentScheduleField = value;
                    this.RaisePropertyChanged("IdParentSchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSchedule {
            get {
                return this.IdScheduleField;
            }
            set {
                if ((this.IdScheduleField.Equals(value) != true)) {
                    this.IdScheduleField = value;
                    this.RaisePropertyChanged("IdSchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManual {
            get {
                return this.IsManualField;
            }
            set {
                if ((this.IsManualField.Equals(value) != true)) {
                    this.IsManualField = value;
                    this.RaisePropertyChanged("IsManual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime KeepDate {
            get {
                return this.KeepDateField;
            }
            set {
                if ((this.KeepDateField.Equals(value) != true)) {
                    this.KeepDateField = value;
                    this.RaisePropertyChanged("KeepDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeepMethod {
            get {
                return this.KeepMethodField;
            }
            set {
                if ((this.KeepMethodField.Equals(value) != true)) {
                    this.KeepMethodField = value;
                    this.RaisePropertyChanged("KeepMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxAirings {
            get {
                return this.MaxAiringsField;
            }
            set {
                if ((this.MaxAiringsField.Equals(value) != true)) {
                    this.MaxAiringsField = value;
                    this.RaisePropertyChanged("MaxAirings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostRecordInterval {
            get {
                return this.PostRecordIntervalField;
            }
            set {
                if ((this.PostRecordIntervalField.Equals(value) != true)) {
                    this.PostRecordIntervalField = value;
                    this.RaisePropertyChanged("PostRecordInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreRecordInterval {
            get {
                return this.PreRecordIntervalField;
            }
            set {
                if ((this.PreRecordIntervalField.Equals(value) != true)) {
                    this.PreRecordIntervalField = value;
                    this.RaisePropertyChanged("PreRecordInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quality {
            get {
                return this.QualityField;
            }
            set {
                if ((this.QualityField.Equals(value) != true)) {
                    this.QualityField = value;
                    this.RaisePropertyChanged("Quality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QualityType {
            get {
                return this.QualityTypeField;
            }
            set {
                if ((this.QualityTypeField.Equals(value) != true)) {
                    this.QualityTypeField = value;
                    this.RaisePropertyChanged("QualityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecommendedCard {
            get {
                return this.RecommendedCardField;
            }
            set {
                if ((this.RecommendedCardField.Equals(value) != true)) {
                    this.RecommendedCardField = value;
                    this.RaisePropertyChanged("RecommendedCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScheduleType {
            get {
                return this.ScheduleTypeField;
            }
            set {
                if ((this.ScheduleTypeField.Equals(value) != true)) {
                    this.ScheduleTypeField = value;
                    this.RaisePropertyChanged("ScheduleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((this.SeriesField.Equals(value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebCard", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CAMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CamTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DecryptLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevicePathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GrabEPGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastEpgGrabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PreloadCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordingFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordingFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeShiftFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int netProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool supportSubChannelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CAM {
            get {
                return this.CAMField;
            }
            set {
                if ((this.CAMField.Equals(value) != true)) {
                    this.CAMField = value;
                    this.RaisePropertyChanged("CAM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CamType {
            get {
                return this.CamTypeField;
            }
            set {
                if ((this.CamTypeField.Equals(value) != true)) {
                    this.CamTypeField = value;
                    this.RaisePropertyChanged("CamType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DecryptLimit {
            get {
                return this.DecryptLimitField;
            }
            set {
                if ((this.DecryptLimitField.Equals(value) != true)) {
                    this.DecryptLimitField = value;
                    this.RaisePropertyChanged("DecryptLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevicePath {
            get {
                return this.DevicePathField;
            }
            set {
                if ((object.ReferenceEquals(this.DevicePathField, value) != true)) {
                    this.DevicePathField = value;
                    this.RaisePropertyChanged("DevicePath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GrabEPG {
            get {
                return this.GrabEPGField;
            }
            set {
                if ((this.GrabEPGField.Equals(value) != true)) {
                    this.GrabEPGField = value;
                    this.RaisePropertyChanged("GrabEPG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCard {
            get {
                return this.IdCardField;
            }
            set {
                if ((this.IdCardField.Equals(value) != true)) {
                    this.IdCardField = value;
                    this.RaisePropertyChanged("IdCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServer {
            get {
                return this.IdServerField;
            }
            set {
                if ((this.IdServerField.Equals(value) != true)) {
                    this.IdServerField = value;
                    this.RaisePropertyChanged("IdServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChanged {
            get {
                return this.IsChangedField;
            }
            set {
                if ((this.IsChangedField.Equals(value) != true)) {
                    this.IsChangedField = value;
                    this.RaisePropertyChanged("IsChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastEpgGrab {
            get {
                return this.LastEpgGrabField;
            }
            set {
                if ((this.LastEpgGrabField.Equals(value) != true)) {
                    this.LastEpgGrabField = value;
                    this.RaisePropertyChanged("LastEpgGrab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PreloadCard {
            get {
                return this.PreloadCardField;
            }
            set {
                if ((this.PreloadCardField.Equals(value) != true)) {
                    this.PreloadCardField = value;
                    this.RaisePropertyChanged("PreloadCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecordingFolder {
            get {
                return this.RecordingFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordingFolderField, value) != true)) {
                    this.RecordingFolderField = value;
                    this.RaisePropertyChanged("RecordingFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordingFormat {
            get {
                return this.RecordingFormatField;
            }
            set {
                if ((this.RecordingFormatField.Equals(value) != true)) {
                    this.RecordingFormatField = value;
                    this.RaisePropertyChanged("RecordingFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeShiftFolder {
            get {
                return this.TimeShiftFolderField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeShiftFolderField, value) != true)) {
                    this.TimeShiftFolderField = value;
                    this.RaisePropertyChanged("TimeShiftFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int netProvider {
            get {
                return this.netProviderField;
            }
            set {
                if ((this.netProviderField.Equals(value) != true)) {
                    this.netProviderField = value;
                    this.RaisePropertyChanged("netProvider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool supportSubChannels {
            get {
                return this.supportSubChannelsField;
            }
            set {
                if ((this.supportSubChannelsField.Equals(value) != true)) {
                    this.supportSubChannelsField = value;
                    this.RaisePropertyChanged("supportSubChannels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebActiveCard", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebActiveCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MPWebStream.TVEInteraction.WebChannel ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRecordingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTimeShiftingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardName {
            get {
                return this.CardNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNameField, value) != true)) {
                    this.CardNameField = value;
                    this.RaisePropertyChanged("CardName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MPWebStream.TVEInteraction.WebChannel Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelField, value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRecording {
            get {
                return this.IsRecordingField;
            }
            set {
                if ((this.IsRecordingField.Equals(value) != true)) {
                    this.IsRecordingField = value;
                    this.RaisePropertyChanged("IsRecording");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTimeShifting {
            get {
                return this.IsTimeShiftingField;
            }
            set {
                if ((this.IsTimeShiftingField.Equals(value) != true)) {
                    this.IsTimeShiftingField = value;
                    this.RaisePropertyChanged("IsTimeShifting");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebRtspClient", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebRtspClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeStartedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreamNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTimeStarted {
            get {
                return this.DateTimeStartedField;
            }
            set {
                if ((this.DateTimeStartedField.Equals(value) != true)) {
                    this.DateTimeStartedField = value;
                    this.RaisePropertyChanged("DateTimeStarted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAdress {
            get {
                return this.IpAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAdressField, value) != true)) {
                    this.IpAdressField = value;
                    this.RaisePropertyChanged("IpAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreamName {
            get {
                return this.StreamNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StreamNameField, value) != true)) {
                    this.StreamNameField = value;
                    this.RaisePropertyChanged("StreamName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebActiveUser", Namespace="http://schemas.datacontract.org/2004/07/TV4Home.Server.TVEInteractionLibrary.Inte" +
        "rfaces")]
    [System.SerializableAttribute()]
    public partial class WebActiveUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MPWebStream.TVEInteraction.WebChannel ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MPWebStream.TVEInteraction.WebChannel Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelField, value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tv4home.codeplex.com", ConfigurationName="TVEInteraction.ITVEInteraction")]
    public interface ITVEInteraction {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/TestConnectionToTVService", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/TestConnectionToTVServiceResponse")]
        bool TestConnectionToTVService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/AddSchedule", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/AddScheduleResponse")]
        void AddSchedule(int channelId, string title, System.DateTime startTime, System.DateTime endTime, int scheduleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/SwitchTVServerToChannelAndGetStreamin" +
            "gUrl", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/SwitchTVServerToChannelAndGetStreamin" +
            "gUrlResponse")]
        string SwitchTVServerToChannelAndGetStreamingUrl(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/SwitchTVServerToChannelAndGetTimeshif" +
            "tFilename", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/SwitchTVServerToChannelAndGetTimeshif" +
            "tFilenameResponse")]
        string SwitchTVServerToChannelAndGetTimeshiftFilename(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/CancelCurrentTimeShifting", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/CancelCurrentTimeShiftingResponse")]
        void CancelCurrentTimeShifting();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetChannels", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetChannelsResponse")]
        MPWebStream.TVEInteraction.WebChannel[] GetChannels(int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetRecordings", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetRecordingsResponse")]
        MPWebStream.TVEInteraction.WebRecording[] GetRecordings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetSchedules", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetSchedulesResponse")]
        MPWebStream.TVEInteraction.WebSchedule[] GetSchedules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetChannelById", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetChannelByIdResponse")]
        MPWebStream.TVEInteraction.WebChannel GetChannelById(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetProgramById", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetProgramByIdResponse")]
        MPWebStream.TVEInteraction.WebProgram GetProgramById(int programId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetProgramsForChannel", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetProgramsForChannelResponse")]
        MPWebStream.TVEInteraction.WebProgram[] GetProgramsForChannel(int channelId, System.DateTime startTime, System.DateTime endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetProgramIsScheduledOnChannel", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetProgramIsScheduledOnChannelRespons" +
            "e")]
        bool GetProgramIsScheduledOnChannel(int channelId, int programId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetProgramIsScheduled", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetProgramIsScheduledResponse")]
        bool GetProgramIsScheduled(out bool isSeries, int programId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/SearchPrograms", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/SearchProgramsResponse")]
        MPWebStream.TVEInteraction.WebProgram[] SearchPrograms(string searchTerm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetGroups", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetGroupsResponse")]
        MPWebStream.TVEInteraction.WebChannelGroup[] GetGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/CancelSchedule", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/CancelScheduleResponse")]
        void CancelSchedule(int programId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetCards", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetCardsResponse")]
        MPWebStream.TVEInteraction.WebCard[] GetCards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetActiveCards", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetActiveCardsResponse")]
        MPWebStream.TVEInteraction.WebActiveCard[] GetActiveCards();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetStreamingClients", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetStreamingClientsResponse")]
        MPWebStream.TVEInteraction.WebRtspClient[] GetStreamingClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetActiveUsers", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetActiveUsersResponse")]
        MPWebStream.TVEInteraction.WebActiveUser[] GetActiveUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/GetCurrentProgramOnChannel", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/GetCurrentProgramOnChannelResponse")]
        MPWebStream.TVEInteraction.WebProgram GetCurrentProgramOnChannel(int channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/Disconnect", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/ReadSettingFromDatabase", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/ReadSettingFromDatabaseResponse")]
        string ReadSettingFromDatabase(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tv4home.codeplex.com/ITVEInteraction/WriteSettingToDatabase", ReplyAction="http://tv4home.codeplex.com/ITVEInteraction/WriteSettingToDatabaseResponse")]
        void WriteSettingToDatabase(string tagName, string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITVEInteractionChannel : MPWebStream.TVEInteraction.ITVEInteraction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TVEInteractionClient : System.ServiceModel.ClientBase<MPWebStream.TVEInteraction.ITVEInteraction>, MPWebStream.TVEInteraction.ITVEInteraction {
        
        public TVEInteractionClient() {
        }
        
        public TVEInteractionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TVEInteractionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TVEInteractionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TVEInteractionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TestConnectionToTVService() {
            return base.Channel.TestConnectionToTVService();
        }
        
        public void AddSchedule(int channelId, string title, System.DateTime startTime, System.DateTime endTime, int scheduleType) {
            base.Channel.AddSchedule(channelId, title, startTime, endTime, scheduleType);
        }
        
        public string SwitchTVServerToChannelAndGetStreamingUrl(int channelId) {
            return base.Channel.SwitchTVServerToChannelAndGetStreamingUrl(channelId);
        }
        
        public string SwitchTVServerToChannelAndGetTimeshiftFilename(int channelId) {
            return base.Channel.SwitchTVServerToChannelAndGetTimeshiftFilename(channelId);
        }
        
        public void CancelCurrentTimeShifting() {
            base.Channel.CancelCurrentTimeShifting();
        }
        
        public MPWebStream.TVEInteraction.WebChannel[] GetChannels(int groupId) {
            return base.Channel.GetChannels(groupId);
        }
        
        public MPWebStream.TVEInteraction.WebRecording[] GetRecordings() {
            return base.Channel.GetRecordings();
        }
        
        public MPWebStream.TVEInteraction.WebSchedule[] GetSchedules() {
            return base.Channel.GetSchedules();
        }
        
        public MPWebStream.TVEInteraction.WebChannel GetChannelById(int channelId) {
            return base.Channel.GetChannelById(channelId);
        }
        
        public MPWebStream.TVEInteraction.WebProgram GetProgramById(int programId) {
            return base.Channel.GetProgramById(programId);
        }
        
        public MPWebStream.TVEInteraction.WebProgram[] GetProgramsForChannel(int channelId, System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetProgramsForChannel(channelId, startTime, endTime);
        }
        
        public bool GetProgramIsScheduledOnChannel(int channelId, int programId) {
            return base.Channel.GetProgramIsScheduledOnChannel(channelId, programId);
        }
        
        public bool GetProgramIsScheduled(out bool isSeries, int programId) {
            return base.Channel.GetProgramIsScheduled(out isSeries, programId);
        }
        
        public MPWebStream.TVEInteraction.WebProgram[] SearchPrograms(string searchTerm) {
            return base.Channel.SearchPrograms(searchTerm);
        }
        
        public MPWebStream.TVEInteraction.WebChannelGroup[] GetGroups() {
            return base.Channel.GetGroups();
        }
        
        public void CancelSchedule(int programId) {
            base.Channel.CancelSchedule(programId);
        }
        
        public MPWebStream.TVEInteraction.WebCard[] GetCards() {
            return base.Channel.GetCards();
        }
        
        public MPWebStream.TVEInteraction.WebActiveCard[] GetActiveCards() {
            return base.Channel.GetActiveCards();
        }
        
        public MPWebStream.TVEInteraction.WebRtspClient[] GetStreamingClients() {
            return base.Channel.GetStreamingClients();
        }
        
        public MPWebStream.TVEInteraction.WebActiveUser[] GetActiveUsers() {
            return base.Channel.GetActiveUsers();
        }
        
        public MPWebStream.TVEInteraction.WebProgram GetCurrentProgramOnChannel(int channelId) {
            return base.Channel.GetCurrentProgramOnChannel(channelId);
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public string ReadSettingFromDatabase(string tagName) {
            return base.Channel.ReadSettingFromDatabase(tagName);
        }
        
        public void WriteSettingToDatabase(string tagName, string value) {
            base.Channel.WriteSettingToDatabase(tagName, value);
        }
    }
}
